#!/usr/bin/env bash
# Build the combined numpy + scipy.ndimage wasm (build/npnd.{mjs,wasm}): the
# numpy C core, the 9 numpy.random extensions AND scipy.ndimage's two compiled
# extensions (_nd_image = 8 plain-C files, _ni_label = Cython) in ONE module,
# so scipy.ndimage's import_array() sees numpy's live PyArray_API. This is the
# first Fortran-free scipy target (NumBry phase 4 / left-half scipy).
#
# Usage: ./ndbuild.sh <scipy-1.14.1-source-tree> <numpy-2.5.1-source-tree>
#
# Prerequisites (all already produced by the pandas build):
#   - numpy-probe/obj/*.o   — numpy C core.
#   - build/nprnd-obj/*.o   — numpy.random (so `import numpy` works on the page).
#   - build/wasthon.o       — current bridge.
#   - Cython 3.0.x importable (CYTHON_PYTHONPATH).
#
# loader/test-scipy-ndimage.html loads build/npnd.mjs (this script) + the numpy
# Python layer (build/numpy_vfs.js, shared with the pandas page) + the scipy
# Python layer, which is generated by:
#   node cython-support/gen_scipy_vfs.mjs <scipy-1.14.1-src>   -> build/scipy_ndimage_vfs.js
set -u
ND="${1:?path to scipy 1.14.1 source tree}"
NP="${2:?path to numpy 2.5.1 source tree}"
CS="$(cd "$(dirname "$0")" && pwd)"; ROOT="$(cd "$CS/.." && pwd)"
SRC="$ROOT/src"
OUT="$ROOT/build/nd-obj"; mkdir -p "$OUT"
cd "$ROOT" && source external/emsdk/emsdk_env.sh >/dev/null 2>&1

NDSRC="$ND/scipy/ndimage/src"
PP="-DCYTHON_USE_TYPE_SPECS=1 -DCYTHON_USE_MODULE_STATE=0 -DCYTHON_FAST_THREAD_STATE=0 -DCYTHON_USE_EXC_INFO_STACK=0 -DCYTHON_USE_TYPE_SLOTS=0 -DCYTHON_USE_PYTYPE_LOOKUP=0 -DCYTHON_USE_UNICODE_INTERNALS=0 -DCYTHON_USE_PYLONG_INTERNALS=0 -DCYTHON_USE_PYLIST_INTERNALS=0 -DCYTHON_ASSUME_SAFE_MACROS=0 -DCYTHON_UNPACK_METHODS=0 -DCYTHON_AVOID_BORROWED_REFS=1 -DPy_OptimizeFlag=0"
NDINC="-I $SRC -I $CS -I $ROOT/numpy-probe/gen -I $ROOT/numpy-probe -I $NP/numpy/_core/include -I $NP/numpy/_core/include/numpy -I $NP/numpy/_core/src/common -I $NDSRC -I $ND/scipy/_lib/src -I $ND/scipy/_build_utils/src"
CFLAGS="-O1 -c -DNDEBUG -DPy_PYTHON_H -DNPY_NO_DEPRECATED_API=0 -DCYTHON_VECTORCALL_TPNEW=0 $PP -Wno-macro-redefined -Wno-int-conversion -Wno-incompatible-pointer-types -include $SRC/patchlevel.h -include $CS/cython_compat.h -include $CS/scipy_compat.h $NDINC"

FAILED=""

# ---- _ni_label: Cython (cimport numpy). Reuse the pandas patch chain (P5/P6
# are no-ops here but harmless).
build_pyx() {  # $1 = dotted module name, $2 = pyx path, $3 = "pxd" to bind the adjacent .pxd
  local MOD="${1##*.}" C="$OUT/${1//./_}.c"
  rm -f "$C"
  if [ "${3:-}" = "pxd" ]; then
    # Cythonize under the SHORT name from the pyx's own directory: the only
    # spelling under which Cython binds the adjacent .pxd (with the dotted
    # --module-name it looks for scipy/ndimage/_cytest.pxd and finds nothing),
    # and the .pxd is what makes Cython emit the __pyx_capi__ exports that
    # LowLevelCallable.from_cython consumes. Same shape as upstream meson
    # (short names from src/). The pages rename the module def to the dotted
    # name at PyInit time.
    ( cd "$(dirname "$2")" && PYTHONPATH="${CYTHON_PYTHONPATH:-}" python3 -m cython -3 -I "$NP" \
      "$(basename "$2")" -o "$C" ) 2>"$OUT/${MOD}_cy.txt"
  else
  PYTHONPATH="${CYTHON_PYTHONPATH:-}" python3 -m cython -3 -I "$NP" \
    --module-name "$1" "$2" -o "$C" 2>"$OUT/${MOD}_cy.txt"
  fi
  if [ ! -f "$C" ]; then echo "$1: CYTHONIZE FAIL"; grep -m3 "error" "$OUT/${MOD}_cy.txt"; return 1; fi
  sed -i 's/def->ml_meth(/((PyCFunction)def->ml_meth)(/g' "$C"
  perl -0pi -e 's/__Pyx_copy_object_array\(src, \(\(PyListObject\*\)res\)->ob_item, n\);/{ Py_ssize_t _i; for(_i=0;_i<n;_i++){ Py_INCREF(src[_i]); PyList_SET_ITEM(res,_i,src[_i]); } }/g' "$C"
  perl -0pi -e 's/#define __Pyx_ArgsSlice_FASTCALL\(args, start, stop\) PyTuple_GetSlice\(args, start, stop\)/#define __Pyx_ArgsSlice_FASTCALL(args, start, stop) __Pyx_PyTuple_FromArray(&__Pyx_Arg_FASTCALL(args, start), stop - start)/g' "$C"
  perl -0pi -e 's|(/\* TupleAndListFromArray(?:\.proto)? \*/\n)#if CYTHON_COMPILING_IN_CPYTHON|${1}#if 1|g' "$C"
  perl -0pi -e 's/__Pyx_copy_object_array\(src, \(\(PyTupleObject\*\)res\)->ob_item, n\);/{ Py_ssize_t _i; for(_i=0;_i<n;_i++){ Py_INCREF(src[_i]); __Pyx_PyTuple_SET_ITEM(res,_i,src[_i]); } }/g' "$C"
  sed -i 's/basicsize = PyLong_AsSsize_t(py_basicsize);/basicsize = PyLong_AsSsize_t(py_basicsize); basicsize = (Py_ssize_t)size;/' "$C"
  perl -0pi -e 's/\(\(PySliceObject\*\)([A-Za-z0-9_]+)\)->(start|stop|step)/__wasthon_slice_$2($1)/g' "$C"
  perl -0pi -e 's/\(\(size_t\)\(basicsize \+ itemsize\) < size\)/(0)/g' "$C"
  perl -0pi -e 's/if \(basicsize != expected_basicsize\) \{/if (0) {/g' "$C"
  local L=$(grep -n "^  #define CYTHON_COMPILING_IN_CPYTHON 1$" "$C" | head -1 | cut -d: -f1)
  [ -n "$L" ] && sed -i "${L}s/#define CYTHON_COMPILING_IN_CPYTHON 1/#define CYTHON_COMPILING_IN_CPYTHON 0/" "$C"
  emcc $CFLAGS "$C" -o "${C%.c}.o" 2>"$OUT/${MOD}_cc.txt"
  local NE=$(grep -c "error:" "$OUT/${MOD}_cc.txt" || true)
  if [ "$NE" != "0" ]; then echo "$1: compile errors=$NE"; grep -m3 "error:" "$OUT/${MOD}_cc.txt"; return 1; fi
  echo "$1: OK"
}

build_pyx "scipy.ndimage._ni_label" "$NDSRC/_ni_label.pyx" || FAILED="$FAILED _ni_label"
# _ccallback_c: required at `import scipy` (scipy._lib._ccallback imports it
# unconditionally). Self-contained Cython (cdef extern from ccallback.h).
build_pyx "scipy._lib._ccallback_c" "$ND/scipy/_lib/_ccallback_c.pyx" || FAILED="$FAILED _ccallback_c"
# _cytest: LowLevelCallable test-support module (test_c_api imports it).
# "pxd" mode: bind the adjacent _cytest.pxd -> __pyx_capi__ exports.
build_pyx "scipy.ndimage._cytest" "$NDSRC/_cytest.pyx" pxd || FAILED="$FAILED _cytest"

# ---- _nd_image: 8 plain-C files. nd_image.c owns the array API import
# (nd_image.h defines PY_ARRAY_UNIQUE_SYMBOL _scipy_ndimage_ARRAY_API); the
# other 7 reference it -> compile them with NO_IMPORT_ARRAY.
# _ctest: plain-C LowLevelCallable test-support module (no numpy)
emcc $CFLAGS "$NDSRC/_ctest.c" -o "$OUT/_ctest.o" 2>"$OUT/_ctest_cc.txt" || FAILED="$FAILED _ctest"
N=$(grep -c 'error:' "$OUT/_ctest_cc.txt" || true); [ "$N" != 0 ] && { echo "_ctest: errors=$N"; grep -m3 'error:' "$OUT/_ctest_cc.txt"; FAILED="$FAILED _ctest"; }
emcc $CFLAGS "$NDSRC/nd_image.c" -o "$OUT/nd_image.o" 2>"$OUT/nd_image_cc.txt" || FAILED="$FAILED nd_image"
N=$(grep -c 'error:' "$OUT/nd_image_cc.txt" || true); [ "$N" != 0 ] && { echo "nd_image: errors=$N"; grep -m3 'error:' "$OUT/nd_image_cc.txt"; }
for F in ni_filters ni_fourier ni_interpolation ni_measure ni_morphology ni_splines ni_support; do
  emcc $CFLAGS -DNO_IMPORT_ARRAY "$NDSRC/$F.c" -o "$OUT/$F.o" 2>"$OUT/${F}_cc.txt" || FAILED="$FAILED $F"
  N=$(grep -c 'error:' "$OUT/${F}_cc.txt" || true); [ "$N" != 0 ] && { echo "$F: errors=$N"; grep -m3 'error:' "$OUT/${F}_cc.txt"; FAILED="$FAILED $F"; }
done

# ---- numpy.fft C++ backend (_pocketfft_umath): scipy.ndimage.fourier needs
# numpy.fft.{r,}fft. Header-only pocketfft (numpy/fft/pocketfft submodule).
# Compiled here (into $OUT so it joins the link) and exported below. Plain
# C-API ufunc module (no Cython/scipy compat headers, unlike $CFLAGS).
em++ -O1 -c -std=c++17 -DNDEBUG -DPy_PYTHON_H -DNPY_NO_DEPRECATED_API=0 -Wno-macro-redefined \
  -include "$SRC/patchlevel.h" -include "$CS/cython_compat.h" $NDINC -I "$NP/numpy/fft" \
  "$NP/numpy/fft/_pocketfft_umath.cpp" -o "$OUT/_pocketfft_umath.o" 2>"$OUT/_pocketfft_umath_cc.txt" \
  || FAILED="$FAILED _pocketfft_umath"
N=$(grep -c 'error:' "$OUT/_pocketfft_umath_cc.txt" || true); [ "$N" != 0 ] && { echo "_pocketfft_umath: errors=$N"; grep -m3 'error:' "$OUT/_pocketfft_umath_cc.txt"; FAILED="$FAILED _pocketfft_umath"; }

echo "=== compile done. FAILED:${FAILED:- none} ==="
ls "$OUT"/*.o 2>/dev/null | wc -l
if [ -n "$FAILED" ]; then echo "compile failures — not linking"; exit 1; fi

# ---- link: numpy core + numpy.random + ndimage + wasthon -> build/npnd.{mjs,wasm}
NR="$ROOT/build/nprnd-obj"
EXP='"_PyInit__multiarray_umath","_wasthon_init","_wasthon_module_create","_malloc","_free","_PyInit__common","_PyInit_bit_generator","_PyInit__mt19937","_PyInit__philox","_PyInit__pcg64","_PyInit__sfc64","_PyInit__bounded_integers","_PyInit__generator","_PyInit_mtrand","_PyInit__nd_image","_PyInit__ni_label","_PyInit__ccallback_c","_PyInit__ctest","_PyInit__cytest","_PyInit__pocketfft_umath"'
CY="$NR/_common.o $NR/bit_generator.o $NR/_mt19937.o $NR/_philox.o $NR/_pcg64.o $NR/_sfc64.o $NR/_bounded_integers.o $NR/_generator.o $NR/mtrand.o"
ALGO="$NR/mt19937.o $NR/mt19937-jump.o $NR/philox.o $NR/pcg64.o $NR/sfc64.o $NR/legacy-distributions.o $NR/legacy_rand_shims.o"
emcc -O1 "$ROOT"/numpy-probe/obj/*.o "$ROOT/build/wasthon.o" "$NR/tanh_stub.o" $CY $ALGO "$NR"/npyrandom/*.o "$OUT"/*.o \
  --js-library "$SRC/wasthon.js" --js-library "$CS/cython_support.js" \
  -s ALLOW_MEMORY_GROWTH=1 -s ALLOW_TABLE_GROWTH=1 -sSTACK_SIZE=5242880 --profiling-funcs \
  -Wl,--allow-multiple-definition -s EXPORTED_FUNCTIONS="[$EXP]" \
  -s EXPORTED_RUNTIME_METHODS='["HEAPU8","HEAP32","UTF8ToString","stringToUTF8","lengthBytesUTF8","wasmTable"]' \
  -s MODULARIZE=1 -s EXPORT_ES6=1 -s EXPORT_NAME=npnd \
  -o "$ROOT/build/npnd.mjs" 2>"$OUT/link_err.txt"
echo "link exit=$? errors=$(grep -c 'error:' "$OUT/link_err.txt")"
grep "undefined symbol" "$OUT/link_err.txt" | sed 's/.*undefined symbol: //' | sort -u
ls -la "$ROOT/build/npnd.wasm" 2>/dev/null | awk '{print "wasm:", $5, "bytes"}'
