#!/usr/bin/env bash
# Build the combined numpy + scipy.special wasm (build/npsp.{mjs,wasm}):
# numpy C core + numpy.linalg (lapack_lite, needed by the dstevr shim) +
# numpy.random + numpy.fft AND scipy.special's nine Fortran-free extensions
# in ONE module. scipy 1.14 eliminated special's Fortran: cephes and the
# rewritten special functions are header-only C++ (special/*.h), the ufunc
# wrappers are generated by _generate_pyx.py (run here, like numpy-probe does
# its own codegen). The single LAPACK routine special needs (dstevr, used by
# ellip_harm) is emulated on lapack_lite's dsteqr_ by cython-support/dstevr_shim.c.
#
# Usage: ./spbuild.sh <scipy-1.14.1-source-tree> <numpy-2.5.1-source-tree>
#
# Prerequisites (all already produced by earlier phases):
#   - numpy-probe/obj/*.o, build/linalg-obj/*.o, build/nprnd-obj/*.o
#   - build/wasthon.o — current bridge.
#   - scipy/_lib/boost_math submodule checked out (build.sh inits it).
#   - Cython importable (CYTHON_PYTHONPATH — the 3.3 fork, same as ndimage).
set -u
ND="${1:?path to scipy 1.14.1 source tree}"
NP="${2:?path to numpy 2.5.1 source tree}"
CS="$(cd "$(dirname "$0")" && pwd)"; ROOT="$(cd "$CS/.." && pwd)"
SRC="$ROOT/src"
OUT="$ROOT/build/sp-obj"; mkdir -p "$OUT"
cd "$ROOT" && source external/emsdk/emsdk_env.sh >/dev/null 2>&1

SP="$ND/scipy/special"
PP="-DCYTHON_USE_TYPE_SPECS=1 -DCYTHON_USE_MODULE_STATE=0 -DCYTHON_FAST_THREAD_STATE=0 -DCYTHON_USE_EXC_INFO_STACK=0 -DCYTHON_USE_TYPE_SLOTS=0 -DCYTHON_USE_PYTYPE_LOOKUP=0 -DCYTHON_USE_UNICODE_INTERNALS=0 -DCYTHON_USE_PYLONG_INTERNALS=0 -DCYTHON_USE_PYLIST_INTERNALS=0 -DCYTHON_ASSUME_SAFE_MACROS=0 -DCYTHON_UNPACK_METHODS=0 -DCYTHON_AVOID_BORROWED_REFS=1 -DPy_OptimizeFlag=0"
# $OUT/inc shadows scipy's lapack_defs.h (written below): the real one pulls
# numpy's whole npy_cblas.h, which assumes numpy internals are already
# included; all special needs from LAPACK is the one dstevr prototype.
BOOST="-I $ND/scipy/_lib/boost_math/include -DBOOST_MATH_STANDALONE=1"
SPINC="-I $OUT/inc -I $SRC -I $CS -I $OUT/work/scipy/special -I $ROOT/numpy-probe/gen -I $ROOT/numpy-probe -I $NP/numpy/_core/include -I $NP/numpy/_core/include/numpy -I $NP/numpy/_core/src/common -I $SP -I $ND/scipy/_lib -I $ND/scipy/_lib/src -I $ND/scipy/_build_utils/src $BOOST"
# All the special extensions live in ONE wasm sharing ONE numpy. Give every TU
# the SAME array/ufunc API pointer (upstream keeps them per-.so; here the .so
# boundary is gone). Without this, ufunc.h's non-static SpecFun_NewUFunc is
# ODR-deduped across _special_ufuncs.cpp/_gufuncs.cpp to a copy that reads a
# per-TU PyUFunc_API nobody set -> null deref -> trap on the first ufunc build.
# The per-TU definitions of the shared symbol merge under --allow-multiple-
# definition (already in the link); whichever module's import_umath runs first
# populates it. Same shape as mplbuild.sh's PY_ARRAY_UNIQUE_SYMBOL.
APISYM="-DPY_ARRAY_UNIQUE_SYMBOL=_scipy_special_ARRAY_API -DPY_UFUNC_UNIQUE_SYMBOL=_scipy_special_UFUNC_API"
SPINC="$SPINC $APISYM"
CFLAGS="-O1 -c -DNDEBUG -DPy_PYTHON_H -DNPY_NO_DEPRECATED_API=0 -DCYTHON_VECTORCALL_TPNEW=0 $PP -Wno-macro-redefined -Wno-int-conversion -Wno-incompatible-pointer-types -include $SRC/patchlevel.h -include $CS/cython_compat.h -include $CS/scipy_compat.h -include $CS/sp_compat.h $SPINC"
# scipy_compat.h is extern "C"-guarded, so give the C++ TUs the same
# recipe-level shims the C TUs get (Py_tp_base, GenericSetDict, PyUnicode_Equal…);
# sp_compat.h then only carries the handful missing from BOTH.
# -fwasm-exceptions (also at link): Boost.Math wrappers throw on domain/
# overflow and catch in-function (boost_special_functions.h erfinv_wrap);
# emscripten's default turns any throw into abort() before the catch —
# cython_special erfinv(±10) killed the wasm runtime mid-suite.
CXXFLAGS="-O1 -c -std=c++17 -fwasm-exceptions -DNDEBUG -DPy_PYTHON_H -DNPY_NO_DEPRECATED_API=0 -DCYTHON_VECTORCALL_TPNEW=0 $PP -Wno-macro-redefined -include $SRC/patchlevel.h -include $CS/cython_compat.h -include $CS/scipy_compat.h -include $CS/sp_compat.h $SPINC"

mkdir -p "$OUT/inc"
cat > "$OUT/inc/lapack_defs.h" <<'EOF'
/* spbuild.sh shadow of scipy/special/lapack_defs.h: same c_dstevr contract,
   bound to cython-support/dstevr_shim.c instead of a real LAPACK. */
#include <stddef.h>
typedef int CBLAS_INT;
#ifdef __cplusplus
extern "C"
#endif
void dstevr_(char *jobz, char *range, int *n, double *d, double *e,
             double *vl, double *vu, int *il, int *iu, double *abstol,
             int *m, double *w, double *z, int *ldz, int *isuppz,
             double *work, int *lwork, int *iwork, int *liwork,
             int *info, size_t jobz_len, size_t range_len);
static void c_dstevr(char *jobz, char *range, CBLAS_INT *n, double *d, double *e,
                     double *vl, double *vu, CBLAS_INT *il, CBLAS_INT *iu, double *abstol,
                     CBLAS_INT *m, double *w, double *z, CBLAS_INT *ldz, CBLAS_INT *isuppz,
                     double *work, CBLAS_INT *lwork, CBLAS_INT *iwork, CBLAS_INT *liwork,
                     CBLAS_INT *info) {
    dstevr_(jobz, range, n, d, e, vl, vu, il, iu, abstol, m,
            w, z, ldz, isuppz, work, lwork, iwork, liwork, info,
            (size_t)1, (size_t)1);
}
EOF

FAILED=""

# ---- codegen + cythonize workdir. The pyx files do relative cimports
# (`from . cimport sf_error`), so unlike ndimage they must be cythonized as a
# real scipy.special package tree: assemble one (static pxd/pxi/pyx + the
# _generate_pyx.py output), cythonize with the dotted --module-name from its
# root. cython_special.pxd sits adjacent under its canonical path, so Cython
# binds it and emits the __pyx_capi__ exports (the _cytest lesson, inverted).
WORK="$OUT/work"; rm -rf "$WORK"; mkdir -p "$WORK/scipy/special"
touch "$WORK/scipy/__init__.py"
cp "$SP"/*.pxd "$SP"/*.pxi "$SP/__init__.py" "$WORK/scipy/special/"
cp "$SP"/_specfun.pyx "$SP"/_comb.pyx "$SP"/_ellip_harm_2.pyx \
   "$SP"/_test_internal.pyx "$SP"/cython_special.pyx "$WORK/scipy/special/"
( cd "$SP" && python3 _generate_pyx.py -o "$WORK/scipy/special" ) \
  2>"$OUT/codegen.txt" || { echo "codegen FAILED"; cat "$OUT/codegen.txt"; exit 1; }

build_pyx() {  # $1 = dotted module name, $2 = "cplus" for C++ mode
  local MOD="${1##*.}" EXT=c CPLUS=
  [ "${2:-}" = "cplus" ] && { EXT=cpp; CPLUS=--cplus; }
  local C="$OUT/${1//./_}.$EXT"
  rm -f "$C"
  ( cd "$WORK" && PYTHONPATH="${CYTHON_PYTHONPATH:-}" python3 -m cython -3 $CPLUS -I . -I "$NP" \
    --module-name "$1" "${1//./\/}.pyx" -o "$C" ) 2>"$OUT/${MOD}_cy.txt"
  if [ ! -f "$C" ]; then echo "$1: CYTHONIZE FAIL"; grep -m3 "error" "$OUT/${MOD}_cy.txt"; return 1; fi
  sed -i 's/def->ml_meth(/((PyCFunction)def->ml_meth)(/g' "$C"
  perl -0pi -e 's/__Pyx_copy_object_array\(src, \(\(PyListObject\*\)res\)->ob_item, n\);/{ Py_ssize_t _i; for(_i=0;_i<n;_i++){ Py_INCREF(src[_i]); PyList_SET_ITEM(res,_i,src[_i]); } }/g' "$C"
  perl -0pi -e 's/#define __Pyx_ArgsSlice_FASTCALL\(args, start, stop\) PyTuple_GetSlice\(args, start, stop\)/#define __Pyx_ArgsSlice_FASTCALL(args, start, stop) __Pyx_PyTuple_FromArray(&__Pyx_Arg_FASTCALL(args, start), stop - start)/g' "$C"
  perl -0pi -e 's|(/\* TupleAndListFromArray(?:\.proto)? \*/\n)#if CYTHON_COMPILING_IN_CPYTHON|${1}#if 1|g' "$C"
  perl -0pi -e 's/__Pyx_copy_object_array\(src, \(\(PyTupleObject\*\)res\)->ob_item, n\);/{ Py_ssize_t _i; for(_i=0;_i<n;_i++){ Py_INCREF(src[_i]); __Pyx_PyTuple_SET_ITEM(res,_i,src[_i]); } }/g' "$C"
  sed -i 's/basicsize = PyLong_AsSsize_t(py_basicsize);/basicsize = PyLong_AsSsize_t(py_basicsize); basicsize = (Py_ssize_t)size;/' "$C"
  perl -0pi -e 's/\(\(PySliceObject\*\)([A-Za-z0-9_]+)\)->(start|stop|step)/__wasthon_slice_$2($1)/g' "$C"
  perl -0pi -e 's/\(\(size_t\)\(basicsize \+ itemsize\) < size\)/(0)/g' "$C"
  perl -0pi -e 's/if \(basicsize != expected_basicsize\) \{/if (0) {/g' "$C"
  local L=$(grep -n "^  #define CYTHON_COMPILING_IN_CPYTHON 1$" "$C" | head -1 | cut -d: -f1)
  [ -n "$L" ] && sed -i "${L}s/#define CYTHON_COMPILING_IN_CPYTHON 1/#define CYTHON_COMPILING_IN_CPYTHON 0/" "$C"
  if [ "$EXT" = "cpp" ]; then
    # The bridge's PyMethodDef declares ml_meth as void*; C++ (unlike C)
    # refuses the implicit function-pointer conversion in the struct
    # initializers, so make the cast explicit there (and only there — the
    # (PyCFunction) CALL casts added above must stay function-typed).
    perl -0pi -e 's/\{"([^"]*)", \(PyCFunction\)/{"$1", (void *)/g' "$C"
    # …and the reverse direction: reading the void* slot back into a
    # typed function pointer.
    perl -0pi -e 's/vectorcallfunc f = __Pyx_PyVectorcall_Function\(func\);/vectorcallfunc f = (vectorcallfunc)__Pyx_PyVectorcall_Function(func);/g' "$C"
    # The unbound-method PyMethodDef feeds a PyCFunction-typed reinterpret
    # into the bridge's void* ml_meth slot — cast it too (C++ only).
    perl -0pi -e 's/(__PYX_REINTERPRET_FUNCION\(PyCFunction, __Pyx_SelflessCall\))/(void *)$1/g' "$C"
    # Cython's CyFunction runtime writes function pointers straight into the
    # bridge's void* slots — ml_meth (the annotate method def) and
    # func_vectorcall (the METH_* dispatch table). C accepts fn-ptr -> void*
    # implicitly; C++ needs the cast at each such site.
    perl -0pi -e 's/\(PyCFunction\)\(void \(\*\)\(void\)\)/(void *)(void (*)(void))/g' "$C"
    perl -0pi -e 's/(__Pyx_CyFunction_func_vectorcall\(op\) = )(__Pyx_CyFunction_Vectorcall_\w+)/${1}(void *)$2/g' "$C"
    # …and reading those void* slots back into typed locals (the CyFunction
    # dispatch reads ml_meth / func_vectorcall to call through them).
    perl -0pi -e 's/(PyCFunction meth = )([^;]*->ml_meth);/${1}(PyCFunction)$2;/g' "$C"
    perl -0pi -e 's/(__pyx_vectorcallfunc vc = )(__Pyx_CyFunction_func_vectorcall\([^;]*\));/${1}(__pyx_vectorcallfunc)$2;/g' "$C"
    # The bridge's code-object constructor is declared PyObject*-returning;
    # Cython assigns it to PyCodeObject* (implicit in C, error in C++). Cast
    # the whole RHS — it straddles an #if, but preprocessor lines nest fine
    # inside the added parens. Scoped to the Code_NewWithPosOnlyArgs site.
    perl -0pi -e 's/(result =)([^;]*Code_NewWithPosOnlyArgs[^;]*);/$1 (PyCodeObject *)($2);/gs' "$C"
    em++ $CXXFLAGS -DCYTHON_EXTERN_C='extern "C"' "$C" -o "${C%.*}.o" 2>"$OUT/${MOD}_cc.txt"
  else
    emcc $CFLAGS "$C" -o "${C%.*}.o" 2>"$OUT/${MOD}_cc.txt"
  fi
  local NE=$(grep -c "error:" "$OUT/${MOD}_cc.txt" || true)
  if [ "$NE" != "0" ]; then echo "$1: compile errors=$NE"; grep -m3 "error:" "$OUT/${MOD}_cc.txt"; return 1; fi
  echo "$1: OK"
}

build_pyx "scipy.special._ufuncs"        || FAILED="$FAILED _ufuncs"
build_pyx "scipy.special._ufuncs_cxx" cplus || FAILED="$FAILED _ufuncs_cxx"
build_pyx "scipy.special.cython_special" || FAILED="$FAILED cython_special"
build_pyx "scipy.special._specfun" cplus || FAILED="$FAILED _specfun"
build_pyx "scipy.special._comb"          || FAILED="$FAILED _comb"
build_pyx "scipy.special._ellip_harm_2"  || FAILED="$FAILED _ellip_harm_2"
build_pyx "scipy.special._test_internal" || FAILED="$FAILED _test_internal"

# ---- plain C/C++ sources
cc_one() {  # $1 = out name, $2 = source path, $3.. = extra flags
  local N="$1" S="$2"; shift 2
  case "$S" in
    *.c) emcc $CFLAGS "$@" "$S" -o "$OUT/$N.o" 2>"$OUT/${N}_cc.txt" ;;
    *)   em++ $CXXFLAGS "$@" "$S" -o "$OUT/$N.o" 2>"$OUT/${N}_cc.txt" ;;
  esac
  local NE=$(grep -c "error:" "$OUT/${N}_cc.txt" || true)
  if [ "$NE" != "0" ]; then echo "$N: compile errors=$NE"; grep -m3 "error:" "$OUT/${N}_cc.txt"; FAILED="$FAILED $N"; fi
}

cc_one sf_error_state "$SP/sf_error_state.c"
cc_one dstevr_shim    "$CS/dstevr_shim.c"
cc_one _cosine        "$SP/_cosine.c"
cc_one cdflib         "$SP/cdflib.c"
cc_one sf_error       "$SP/sf_error.cc" -DSP_SPECFUN_ERROR
cc_one special_wrappers "$SP/special_wrappers.cpp"
cc_one dd_real_wrappers "$SP/dd_real_wrappers.cpp"
cc_one _special_ufuncs      "$SP/_special_ufuncs.cpp" -DSP_SPECFUN_ERROR
cc_one _special_ufuncs_docs "$SP/_special_ufuncs_docs.cpp"
cc_one _gufuncs      "$SP/_gufuncs.cpp" -DSP_SPECFUN_ERROR
cc_one _gufuncs_docs "$SP/_gufuncs_docs.cpp"
BOOST="-I $ND/scipy/_lib/boost_math/include -DBOOST_MATH_STANDALONE=1"
cc_one Faddeeva  "$SP/Faddeeva.cc" $BOOST
cc_one wright    "$SP/wright.cc" $BOOST
cc_one _faddeeva "$SP/_faddeeva.cxx" $BOOST
cc_one _wright   "$SP/_wright.cxx" $BOOST
cc_one ellint_carlson_wrap "$SP/ellint_carlson_wrap.cxx" $BOOST

# _ccallback_c: required at `import scipy` (also built by ndbuild; rebuilt
# here so spbuild stands alone). Same patch chain as the special modules.
mkdir -p "$WORK/scipy/_lib"; touch "$WORK/scipy/_lib/__init__.py"
cp "$ND/scipy/_lib/_ccallback_c.pyx" "$ND/scipy/_lib/ccallback.pxd" "$WORK/scipy/_lib/"
build_pyx "scipy._lib._ccallback_c" || FAILED="$FAILED _ccallback_c"

# numpy.fft C++ backend, same as ndbuild (np.fft available on the page)
em++ -O1 -c -std=c++17 -DNDEBUG -DPy_PYTHON_H -DNPY_NO_DEPRECATED_API=0 -Wno-macro-redefined \
  -include "$SRC/patchlevel.h" -include "$CS/cython_compat.h" $SPINC -I "$NP/numpy/fft" \
  "$NP/numpy/fft/_pocketfft_umath.cpp" -o "$OUT/_pocketfft_umath.o" 2>"$OUT/_pocketfft_umath_cc.txt" \
  || FAILED="$FAILED _pocketfft_umath"

echo "=== compile done. FAILED:${FAILED:- none} ==="
ls "$OUT"/*.o 2>/dev/null | wc -l
if [ -n "$FAILED" ]; then echo "compile failures — not linking"; exit 1; fi

# ---- link -> build/npsp.{mjs,wasm}
NR="$ROOT/build/nprnd-obj"; LA="$ROOT/build/linalg-obj"
EXP='"_PyInit__multiarray_umath","_PyInit__umath_linalg","_wasthon_init","_wasthon_module_create","_malloc","_free","_PyInit__common","_PyInit_bit_generator","_PyInit__mt19937","_PyInit__philox","_PyInit__pcg64","_PyInit__sfc64","_PyInit__bounded_integers","_PyInit__generator","_PyInit_mtrand","_PyInit__pocketfft_umath","_PyInit__ccallback_c","_PyInit__ufuncs","_PyInit__ufuncs_cxx","_PyInit__special_ufuncs","_PyInit__gufuncs","_PyInit__specfun","_PyInit_cython_special","_PyInit__comb","_PyInit__ellip_harm_2","_PyInit__test_internal"'
CY="$NR/_common.o $NR/bit_generator.o $NR/_mt19937.o $NR/_philox.o $NR/_pcg64.o $NR/_sfc64.o $NR/_bounded_integers.o $NR/_generator.o $NR/mtrand.o"
ALGO="$NR/mt19937.o $NR/mt19937-jump.o $NR/philox.o $NR/pcg64.o $NR/sfc64.o $NR/legacy-distributions.o"
emcc -O1 -fwasm-exceptions "$ROOT"/numpy-probe/obj/*.o "$LA"/*.o "$ROOT/build/wasthon.o" "$NR/tanh_stub.o" $CY $ALGO "$NR"/npyrandom/*.o "$OUT"/*.o \
  --js-library "$SRC/wasthon.js" --js-library "$CS/cython_support.js" \
  -s ALLOW_MEMORY_GROWTH=1 -s ALLOW_TABLE_GROWTH=1 -sSTACK_SIZE=5242880 --profiling-funcs \
  -Wl,--allow-multiple-definition -s EXPORTED_FUNCTIONS="[$EXP]" \
  -s EXPORTED_RUNTIME_METHODS='["HEAPU8","HEAP32","UTF8ToString","stringToUTF8","lengthBytesUTF8","wasmTable"]' \
  -s MODULARIZE=1 -s EXPORT_ES6=1 -s EXPORT_NAME=npsp \
  -o "$ROOT/build/npsp.mjs" 2>"$OUT/link_err.txt"
echo "link exit=$? errors=$(grep -c 'error:' "$OUT/link_err.txt")"
grep "undefined symbol" "$OUT/link_err.txt" | sed 's/.*undefined symbol: //' | sort -u
ls -la "$ROOT/build/npsp.wasm" 2>/dev/null | awk '{print "wasm:", $5, "bytes"}'
